### ISSUE TITLE
birthMonth decoding issue

### ISSUE THREAD

**Issue by GieltjE** [Sikerdebaard/coronacheck-tools#2]
There seems to be a minor decoding issue with the current app (from RAW and QR): "birthMonth": "\u0000"

Full raw or QR code can be supplied in private.

**Comment by Sikerdebaard** [comment]
What would be the expected result? This seems to be a null-char, is that correct?

**Comment by GieltjE** [comment]
It looks like a null byte, isn't it supposed to contain a 1-12 number?

**Comment by Sikerdebaard** [comment]
It depends. Could you send me an example script + raw / QR? sikerdebaard@gmail.com

**Comment by GieltjE** [comment]
You should have an email.

**Comment by Sikerdebaard** [comment]
Is this a QR code of a negative test result? I haven't parsed that one through my tool yet but it looks like the data was deserialized properly. The app QR code after vaccination usually contains the birthMonth and not the birthDay field. Looks like it's the other way around for this particular QR.

**Comment by GieltjE** [comment]
This is a coronacheck app result after 2 vacinations, the birthDay field is correct but somehow the month is omitted.

**Comment by Sikerdebaard** [comment]
There really isn't any other data in that particular field for this QR. I guess they generate the QR with birthDay left out and somtimes with birthMonth left out. Mine has birthDay left out for example.

You can verify this by going to your coronacheck app and pressing the ? icon on the top right while displaying the Dutch QR code.  Under 'your details' It'll show the data inside the QR. In your case it probably has an underscore instead of a month but your birthDay should be filled in. As well as your firstName and lastName initials.

**Comment by GieltjE** [comment]
You are correct, sorry for the inconveinience.

**Comment by Sikerdebaard** [comment]
No problem. Good luck with your project. ;)

**Comment by GieltjE** [comment]
Thanks, do you by any chance have a clue on how to validate the other data against the governments certificates?

**Comment by Sikerdebaard** [comment]
What do you mean with other data?

This tool can verify a QR code either through the CLI tool or through the Python API if thats what you mean. It uses a thin wrapper around the governments mobilecore verifier. Similar to the coronacheck scanner app. The QR that you supplied is considered invalid.

CLI tool: https://github.com/Sikerdebaard/coronacheck-tools#verify

Python API example: https://github.com/Sikerdebaard/coronacheck-tools/blob/main/examples/qr_validator.py

Your particular QR is not valid.
```bash
coronacheck-tools verify qr ./QR.jpg 
This is an unofficial tool that is in no way affiliated with CoronaCheck.nl or the Ministry of VWS
Code is invalid Could not verify domestic QR code: The credential has been generated too long ago, or clock skew is too large
```

**Comment by GieltjE** [comment]
That indeed validates them, but their lifespan is pretty short (which is good I guess), many thanks!

**Comment by Sikerdebaard** [comment]
Try the paper one. That one skips the time based challenge. Last time I checked it was valid for a year.

https://coronacheck.nl/nl/print/
