### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by MaartenW** [Sikerdebaard/coronacheck-tools#4]
It seems like the package is dependent on:
`libGL.so.1` & `zbar` which, in my case, could be solved by:
```
sudo apt-get install libgl1-mesa-glx zbar-tools
```

**Comment by Sikerdebaard** [comment]
Nice catch. I should probably add that to the readme one of these days.

The dockerfiles contain these as well: https://github.com/Sikerdebaard/coronacheck-tools/blob/main/docker/Dockerfile.pub

**Comment by Sikerdebaard** [comment]
Dependancies have been added to the README.md
