### ISSUE TITLE
Question about c, a and response fields

### ISSUE THREAD

**Issue by Theagainmen** [Sikerdebaard/coronacheck-tools#6]
Hey there,

Thanks for your cool repo about seeing what's inside the QR code! Really interesting stuff.
I was wondering what the c, a, eResponse, vResponse and aResponse fields mean. They seem to be still encoded? What is in this fields? They seem to change with every QR code too. Is there a page where I can find more information about this?

Thanks for any help :)

**Comment by Sikerdebaard** [comment]
These fields are part of the idemix proof. I'm no expert on that, it seems pretty bleeding edge crypto tech. The fields are not meant to contain human readable data.

The mobilecore verifier uses the [gabi library](https://github.com/privacybydesign/gabi) to validate the proof. The relevant code path for this [starts here](https://github.com/minvws/nl-covid19-coronacheck-idemix/blob/d798393c2e83750dd9fb21614c98d94837260607/verifier/verifier.go#L84).
