### ISSUE TITLE
proofIdentifierDenylist

### ISSUE THREAD

**Issue by fobrs** [Sikerdebaard/coronacheck-tools#7]
In de officiele scanner app is nu in de config file een proofIdentifierDenylist opgenomen waarmee kennelijk de geldigheid van individuele qr codes uitgeschakeld kan worden.  Kan deze  'ProofIdentifier' ook met deze tools geprint worden?

https://github.com/minvws/nl-covid19-coronacheck-idemix/commit/21fbb94f41510fe23356c42c4888520dd03b1acb

**Comment by Sikerdebaard** [comment]
Oeps, de commit triggert een close van dit ticket. Dat was niet helemaal de bedoeling. :)

Ik heb een nieuwe versie released die overweg kan met de `proofIdentifierDenylist`. Je kan upgraden door of je docker image opnieuw te pullen of door een `pip install --upgrade coronacheck-tools` te draaien.

Het is aan te raden om je config te cleanen door een `coronacheck-tools clean` te draaien, dan weet je zeker dat de config voor de mobilecore verifier up-to-date is, die wordt dan namelijk automatisch opnieuw gedownload. Als je vervolgens een revoked QR code valideert dan krijg je deze output: 

```bash
$ coronacheck-tools verify json /tmp/testout/dhc_data_000.json 
This is an unofficial tool that is in no way affiliated with CoronaCheck.nl or the Ministry of VWS
Code is invalid Could not verify domestic QR code: The credential identifier was present in the proof identifier denylist
```

Om de `proofIdentifierDenylist` uit de config uit te lezen heb ik het config command toegevoegd. Je kan die draaien zonder parameter en dan dumpt het de gehele config, of je kan een key meegeven en dan dumpt het alleen wat onder die key staat in de config. Bijvoorbeeld:

```bash
$ coronacheck-tools config proofIdentifierDenylist
This is an unofficial tool that is in no way affiliated with CoronaCheck.nl or the Ministry of VWS
{
  "11JoX+77S9vVjWskiii1Vg==": true,
  "3WdXZa6TgISdEEKQGVTq7A==": true,
  "8rbKvX+ulRBmHxI8tCqwKA==": true,
  "BmNzE2lU15G5yBINksLyrQ==": true,
  "FIT4zH3FVeh5z1PQj7X5bw==": true,
  "HnvtFd2Brb7rIDvXN7LMBg==": true,
  "JyoXN+LkbWEjqBvte11m8w==": true,
  "KNOT40ctHWE8XTekU1vo1w==": true,
  "PLC3+Pz671j+bNtF1ZP7wQ==": true,
  "QkvWtuawgmzD/9sLtooeFw==": true,
  "Rmgd3gvUirnwn8f2HrfvJg==": true,
  "XHQw55X9pMTWxv840FkVjw==": true,
  "ofVzPyvdTc4jcZXzDwzVcA==": true
}
```

Zoals je in je mail aangaf is het niet te hopen dat voor elke revoked QR code een lijntje aan de config toegevoegd moet worden want dan wordt het snel onhandelbaar.

**Comment by fobrs** [comment]
Ok, bedankt voor je super snelle update!

Maar is er ook een commando waarmee ik de proofidentifier of zoals jij hem noemt de credential indentifier van een qr code kan zien?
Zou wel graag willen weten of die identifier uniek is voor de die ene qr code of voor de persoon.

Hij wordt uit de eerste 128 bit van de c-waarde gehaald. Weet jij waar die c-waarde voor staat?

**Comment by fobrs** [comment]
Er zijn recent nieuwe codes in de proofIdentifierDenylist lijsten geplaatst. De volgende internationale code wordt door de verify tool als geldig aangemerkt terwijl de offciele scanner app  de code ongeldig verkaard.
`coronacheck-tools verify -e RAW hc1.raw
 `
hc1.raw attached
[hc1.zip](https://github.com/Sikerdebaard/coronacheck-tools/files/7490150/hc1.zip)

**Comment by Sikerdebaard** [comment]
In principe valt de internationale QR code buiten de scope van deze library.

Zo te zien is er een update geweest van de [mobilecore](https://github.com/minvws/nl-covid19-coronacheck-mobile-core) verifier van MinVWS. Ik ben de coronacheck-tools library aan het rebuilden met de nieuwe versie en update je zodra dit process voltooid is.

**Comment by Sikerdebaard** [comment]
Er is een nieuwe versie van coronacheck-tools met de updated mobilecore. Upgraden kan door een `pip install --upgrade coronacheck-tools` te draaien. Wanneer je de hc1.raw hierin verified dan zal de library aangeven dat de QR code op de denylist staat.

De raspberry pi build draait nog op de oude mobilecore versie omdat het builden hiervan problemen geeft. Dit hoop ik in de komende dagen op te lossen en dan zal er een nieuwe release volgen.

**Comment by Bart0110** [comment]
> Er is een nieuwe versie van coronacheck-tools met de updated mobilecore. Upgraden kan door een `pip install --upgrade coronacheck-tools` te draaien. Wanneer je de hc1.raw hierin verified dan zal de library aangeven dat de QR code op de denylist staat.
> 
> De raspberry pi build draait nog op de oude mobilecore versie omdat het builden hiervan problemen geeft. Dit hoop ik in de komende dagen op te lossen en dan zal er een nieuwe release volgen.

Lijkt erop dat de denylist command nog niet de ondersteuning heeft om dit te doen: `coronacheck-tools denylist raw .\hc1.raw`

```
at C:\Python\lib\site-packages\coronacheck_tools\api\decoder.py:53 in decode_raw
      49│
      50│
      51│ def decode_raw(raw, format='dict', version='auto'):
      52│     if not (raw.startswith('NL') and raw[3] == ':'):
    → 53│         raise ValueError(f'Invalid data. RAW data should start with NLx: {raw}')
      54│
      55│     if version == 'auto':
      56│         version = int(raw[2], 16)
      57│```

**Comment by Sikerdebaard** [comment]
Deze library focust op de domestic DHC QR code. Je probeert hier een internationaal EHC QR code aan het denylist command mee te geven. Dat gaat niet werken.

Het verify command daarintegen kan via de mobilecore library van MinVWS alsnog een EHC verifyen. Dit doe je als volgt: `coronacheck-tools verify raw hc1.raw`
