### ISSUE TITLE
Updates to denylist?

### ISSUE THREAD

**Issue by buzztiaan** [Sikerdebaard/coronacheck-tools#9]
Hey,

 As there's now 23 keys that have been added to deny-list, I would like to see a update to this.
 Any idea how we could streamline adding newly denied QRs?

**Comment by buzztiaan** [comment]
also, does anyone know why the issue keys of these 23 didn't get revoked?

**Comment by Sikerdebaard** [comment]
I'm not sure what your question is here. The library already supports the denylist for domestic QR codes. E.g. `coronacheck-tools denylist --help` or when a QR code on the denylist is passed to `coronacheck-tools verify --help` it gets declined by the mobilecore verifier. 

Should you wish to see the mobilecore config, that contains both the EU and domestic denylist you could run something like this to retrieve those lists: 
domestic denylist: `coronacheck-tools config | tail -n +2 | jq '.. | .domesticVerificationRules.proofIdentifierDenylist? // empty'`
eu denylist: `coronacheck-tools config | tail -n +2 | jq '.. | .europeanVerificationRules.proofIdentifierDenylist? // empty'`

**Comment by buzztiaan** [comment]
ah, on updating to v4, the denylist shows em all, closing
